# Generated by Django 3.2.7 on 2021-09-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='City')),
                ('create_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Create at')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='Weather.weatherapp', verbose_name='Weather')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['-create_at'],
            },
        ),
    ]
