version: "3.9"

services:
  db:
    container_name: dwr_database
    restart: always
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ytrewq
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  django:
    image: django_weather_remider
    restart: always
    container_name: dwr_app
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/dwr_rest/manage.py makemigrations --noinput &&
             python /usr/src/dwr_rest/manage.py migrate --noinput &&
             python /usr/src/dwr_rest/manage.py collectstatic --noinput &&
             python /usr/src/dwr_rest/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/dwr_rest
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
    container_name: dwr_redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - django
  celery:
    build: .
    image: celery
    container_name: dwr_celery
    command: celery -A DjangoWeatherRemider worker -l INFO
    volumes:
      - .:/usr/src/dwr_rest
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    image: celery-beat
    container_name: dwr_celery_beat
    command: celery -A DjangoWeatherRemider beat -l INFO
    volumes:
      - .:/usr/src/dwr_rest
    depends_on:
      - db
      - redis
  flower:
    image: mher/flower
    container_name: dwr_flower
    command: celery flower -A DjangoWeatherRemider --broker=redis://localhost:6379/0
    volumes:
      - .:/usr/src/dwr_rest
    working_dir: /dwr_rest
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - celery
      - redis
volumes:
  postgres_data:
