# Generated by Django 3.2.7 on 2021-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Create at')),
                ('update', models.SmallIntegerField(choices=[(3, 3), (6, 6), (9, 9), (12, 12), (24, 24)], default=3, verbose_name='Notice period')),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weather',
                'ordering': ['-create_at'],
            },
        ),
    ]
