# Generated by Django 3.2.7 on 2021-09-18 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Create at')),
                ('temp', models.CharField(blank=True, max_length=5, null=True, verbose_name='Temperature in C')),
                ('feels_like', models.CharField(blank=True, max_length=5, null=True, verbose_name='Feels like in C')),
                ('pressure', models.CharField(blank=True, max_length=5, null=True, verbose_name='Pressure')),
                ('visibility', models.CharField(blank=True, max_length=20, null=True, verbose_name='Visibility')),
                ('wind', models.CharField(blank=True, max_length=10, null=True, verbose_name='Wind m.s')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Icon')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='City.cityapp', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weather',
                'ordering': ['-create_at'],
            },
        ),
    ]
