# Generated by Django 3.2.7 on 2021-09-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_remove_cityapp_weather'),
        ('Weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherapp',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='City.cityapp', verbose_name='Cityr'),
        ),
    ]
