# Generated by Django 3.2.7 on 2021-09-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_remove_cityapp_weather'),
        ('Weather', '0002_weatherapp_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherapp',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='City.cityapp', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='weatherapp',
            name='update',
            field=models.SmallIntegerField(choices=[(3, 3), (6, 6), (9, 9), (12, 12), (24, 24)], verbose_name='Notice period'),
        ),
    ]
